version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/12345678  
    ports:
      - "7687:7687"  # Bolt
      - "7474:7474"  # HTTP
    networks:
      - mynetwork

  origen_datos:
    build:
      context: ./origen_datos
    volumes:
      - ./origen_datos/datos:/datos
    networks:
      - mynetwork

  procesamiento_datos:
    build:
      context: ./procesamiento_datos
    depends_on:
      - origen_datos
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
