version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/12345678  
    ports:
      - "7687:7687"  # Bolt
      - "7474:7474"  # HTTP
    networks:
      - mynetwork

  origen_datos:
    build:
      context: ./origen_datos
    volumes:
      - datos:/datos
    networks:
      - mynetwork

  procesamiento_datos:
    build:
      context: ./procesamiento_datos
    depends_on:
      - neo4j
      - origen_datos
    volumes:
      - datos:/datos
    networks:
      - mynetwork

  frontend:
    build:
      context: ./explotacion_datos
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  backend:
    build:
      context: ./explotacion_datos
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - neo4j
    networks:
      - mynetwork

volumes:
  datos:

networks:
  mynetwork:
    driver: bridge
