version: '3.9'

services:
  origen_datos:
    build:
      context: ./origen_datos
    volumes:
      - datos:/datos
    networks:
      - mynetwork

  procesamiento_datos:
    build:
      context: ./procesamiento_datos
    depends_on:
      - origen_datos
    volumes:
      - datos:/datos
    networks:
      - mynetwork

volumes:
  datos:

networks:
  mynetwork:
    external: true
